default:
  image: docker/compose

stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  VIRTUAL_HOST: ${VIRTUAL_HOST}
  VIRTUAL_PORT: ${VIRTUAL_PORT}
  LETSENCRYPT_EMAIL: ${USER_EMAIL}

build:
  stage: build
  script:
    - docker compose build
  tags:
    - main


deploy:
  stage: deploy
  script:
    - docker compose up -d
  tags:
    - main
  when: manual
