default:
  image: docker/compose

stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2


build:
  stage: build
  script:
    - docker compose build
  tags:
    - main


deploy:
  stage: deploy
  script:
    - REDIS_HOST=pyshort_redis
    - VIRTUAL_HOST=${VIRTUAL_HOST}
    - VIRTUAL_PORT=${VIRTUAL_PORT}
    - LETSENCRYPT_EMAIL=${USER_EMAIL}
    - docker compose up -d
  tags:
    - main
