default:
  image: docker/compose

stages:
  - prepare
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2

prepare:
  stage: prepare
  script:
    - bash set_env.sh

build:
  stage: build
  script:
    - docker-compose build
  tags:
    - main


deploy:
  stage: deploy
  script:
    - docker-compose up -d
  tags:
    - main
