services:
  cache:
    image: redis
    networks:
      - internal
  pyshort_flask:
    depends_on:
      - cache
    image: reg.rei.ms/wolf/pyshort:arm
    environment:
      REDIS_HOST: cache
      url: https://${PYSHORT_URL}
    labels:
      traefik.enable: "true"
      traefik.http.routers.pyshort.rule: "Host(`${PYSHORT_URL}`)"
      traefik.docker.network: "traefik"
      traefik.http.routers.pyshort.entrypoints: "websecure"
      traefik.http.routers.pyshort.service: pyshort
      traefik.http.routers.pyshort.certresolver: "le-ssl"
      traefik.http.services.pyshortloadbalancer.port: "5000"
    networks:
      - traefik
      - internal


networks:
  traefik:
    external: true
  internal:
    external: false
