version: '3.1'

services:
  pyshort_redis:
    image: redis
  pyshort_flask:
    depends_on:
      - pyshort_redis
    image: agirault/pyshort
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      REDIS_HOST: pyshort_redis
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      VIRTUAL_PORT: ${VIRTUAL_PORT}
      LETSENCRYPT_EMAIL: ${USER_EMAIL}
      LETSENCRYPT_HOST: ${VIRTUAL_HOST}
      url: https://${VIRTUAL_HOST}
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
