services:
  cache:
    image: redis

  pyshort:
    depends_on:
      - cache
    image: reg.rei.ms/wolf/pyshort
    environment:
      REDIS_HOST: cache
      url: https://${PYSHORT_HOST}
      PYSHORT_HOST: ${PYSHORT_HOST}
    networks:
      - internal

networks:
  internal:
    external: false
