# Generated by Django 5.1.1 on 2024-10-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortenerapp", "0002_redirectionlink_creation_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="redirectionlink",
            name="shortened_link",
        ),
        migrations.AddField(
            model_name="redirectionlink",
            name="hash_link",
            field=models.CharField(default="", max_length=8),
            preserve_default=False,
        ),
    ]
